repos:
  - repo: local
    hooks:
      - id: check-poetry
        name: Poetry check
        description: Validates the structure of the pyproject.toml file
        language: python
        entry: poetry check
        pass_filenames: false
        files: pyproject.toml
        always_run: true
        additional_dependencies: [poetry]

  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.21.4
    hooks:
      - id: nitpick

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [flake8-blind-except, flake8-bugbear, flake8-comprehensions,
          flake8-debugger, flake8-docstrings, flake8-isort, flake8-polyfill, flake8-pytest,
          flake8-quotes, yesqa]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.1.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks

  - repo: https://github.com/openstack/bashate
    rev: 2.0.0
    hooks:
      - id: bashate

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.1
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--safe, --quiet]

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.6.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==19.10b0]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
